name: "Publish Docker Image"

on:
  workflow_call:
    # No inputs needed at this time

jobs:
  docker_publish:
    runs-on: ubuntu-latest
    permissions:
      attestations: write
      contents: read
      id-token: write
      packages: write

    env:
      DOCKER_IO_REGISTRY: docker.io
      DOCKER_IO_IMAGE_NAME_ALL: helmuthva/oe-python-template
      DOCKER_IO_IMAGE_NAME_SLIM: helmuthva/oe-python-template-slim

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Install dev tools
        shell: bash
        run: .github/workflows/_install_dev_tools.bash

      - name: Set up QEMU
        uses: docker/setup-qemu-action@29109295f81e9208d7d86ff1c6c12d2833863392 # v3.6.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2 # v3.10.0


      - name: "(all target): Build and push Docker image"
        id: build-and-push-all
        uses: docker/build-push-action@471d1dc4e07e5cdedd4c2171150001c434f0b7a4 # v6.15.0
        with:
          context: .
          file: ./Dockerfile
          target: all
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta-all.outputs.tags }}
          labels: ${{ steps.meta-all.outputs.labels }}



      - name: "(slim target): Build and push Docker image"
        id: build-and-push-slim
        uses: docker/build-push-action@471d1dc4e07e5cdedd4c2171150001c434f0b7a4 # v6.15.0
        with:
          context: .
          file: ./Dockerfile
          target: slim
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta-slim.outputs.tags }}
          labels: ${{ steps.meta-slim.outputs.labels }}





      - name: "(all target): Generate artifact attestation"
        uses: actions/attest-build-provenance@c074443f1aee8d4aeeae555aebba3282517141b2 # v2.2.3
        with:
          subject-name: ${{ env.DOCKER_IO_REGISTRY }}/${{ env.DOCKER_IO_IMAGE_NAME_ALL }}
          subject-digest: ${{ steps.build-and-push-all.outputs.digest }}
          push-to-registry: true




      - name: "(slim target): Generate artifact attestation"
        uses: actions/attest-build-provenance@c074443f1aee8d4aeeae555aebba3282517141b2 # v2.2.3
        with:
          subject-name: ${{ env.DOCKER_IO_REGISTRY }}/${{ env.DOCKER_IO_IMAGE_NAME_SLIM }}
          subject-digest: ${{ steps.build-and-push-slim.outputs.digest }}
          push-to-registry: true